# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fa32bbde27ae9187caf369be740fb43154d5cdbd8006fba76b6cec83dae6ccb805a9b7ddfe06a204667eff728ee577faef4f8b5b31f4a7b735748dd3a65d2ad

test:
  secret_key_base: d9ce985bede58016dae2cf94597420b12b93be25e268a8735b5e0633f0bc5e1c0a88d2ee7414d3b8349e7e6c4f7967ea3698652826d367c854336da6edfc3385

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
